baseURL = "http://vinzi-wuestenrose.at/"
languageCode = "de-de"
paginate = 6
summaryLength = "10"
theme = "wishfund-hugo"
title = "Vinzenzgemeinschaft Bezirk Murau - Wuestenrose"
[[menu.footer]]
URL = "contact"
name = "Kontakt"
weight = 3
[[menu.footer]]
URL = "impressum"
name = "Impressum"
weight = 2
[[menu.footer]]
URL = "datenschutz"
name = "Datenschutz"
weight = 1
[[menu.main]]
URL = "donation"
name = "Spende"
parent = "HELFEN"
weight = 1
[[menu.main]]
URL = "volunteer"
name = "Ehrenamt"
parent = "HELFEN"
weight = 2
[[menu.main]]
URL = "contact"
name = "KONTAKT"
weight = 6
[[menu.main]]
URL = "event"
name = "TERMINE"
weight = 5
[[menu.main]]
hasChildren = true
name = "HELFEN"
weight = 4
[[menu.main]]
URL = "causes"
name = "PROJEKTE"
weight = 3
[[menu.main]]
URL = "blog"
name = "AKTUELLES"
weight = 2
[[menu.main]]
URL = "about"
name = "ÜBER UNS"
weight = 1
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Themefisher"
copyright = "&copy; 2021 Vinzenzgemeinschaft Murau"
description = "This is meta description"
email = "info@vinzi-wuestenrose.at"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
googleAnalitycsID = "Your ID"
home = "START"
location = "A-8844 Schöder"
logo = "images/logoBlack.png"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
phone = "+43 650 3536751"
[params.navBtn]
enable = true
label = "SPENDEN"
link = "donation"
[[params.plugins.css]]
URL = "plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/themify/css/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/magnific-popup/dist/magnific-popup.css"
[[params.plugins.css]]
URL = "plugins/slick-carousel/slick/slick.css"
[[params.plugins.js]]
URL = "plugins/jquery/jquery.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/magnific-popup/dist/jquery.magnific-popup.min.js"
[[params.plugins.js]]
URL = "plugins/slick-carousel/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"
[[params.plugins.js]]
URL = "plugins/google-map/map.js"
[params.preloader]
enable = true
[params.topHeader]
enable = true
[[params.postShare]]
icon = "ti-facebook"
link = "https://www.facebook.com/profile.php?id=100063577989432"
name = "facebook"
[[params.postShare]]
icon = "ti-twitter-alt"
link = "#"
name = "twitter"
[[params.postShare]]
icon = "ti-linkedin"
link = "#"
name = "linkedin"
[[params.postShare]]
icon = "ti-pinterest"
link = "#"
name = "pinterest"
[[params.social]]
icon = "ti-facebook"
link = "#"
name = "Facebook"
