######################## default configuration ####################
baseURL = "https://www.vinzi-wuestenrose.at"
#"https://vinzi-wuestenrose.netlify.app"
languageCode = "de-de"
title = "Vinzenzgemeinschaft Bezirk Murau - Wuestenrose"
theme = "wishfund-hugo"
summaryLength = "20"
paginate = 6

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]

######################### Plugins #################################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/css/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/themify/css/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/magnific-popup/dist/magnific-popup.css"
  [[params.plugins.css]]
  URL = "plugins/slick-carousel/slick/slick.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jquery/jquery.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/js/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/magnific-popup/dist/jquery.magnific-popup.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick-carousel/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/reading-time/readingTime.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/map.js"
  
############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "ÜBER UNS"
  URL = "about"
  weight = 2
  
  [[menu.main]]
  name = "AKTUELLES"
  URL = "blog"
  weight = 3
  
  [[menu.main]]
  name = "PROJEKTE"
  URL = "causes"
  weight = 4

  [[menu.main]]
  weight = 5
  name = "HELFEN"
  hasChildren = true

    [[menu.main]]
    parent = "HELFEN"
    name = "Spende"
    URL = "donation"

    [[menu.main]]
    parent = "HELFEN"
    name = "Ehrenamt"
    URL = "volunteer"
  
  [[menu.main]]
  name = "TERMINE"
  URL = "event"
  weight = 6
    
  [[menu.main]]
  name = "KONTAKT"
  URL = "contact"
  weight = 7

  ################# footer menu ##################

  [[menu.footer]]
  name = "Datenschutz"
  URL = "datenschutz" ###tbd
  weight = 1

  [[menu.footer]]
  name = "Impressum"
  URL = "impressum" ###tbd
  weight = 2

  [[menu.footer]]
  name = "Kontakt"
  URL = "contact"
  weight = 3
  
  ##[[menu.footer]]
  ##name = "Cookie-Einstellungen"
  ##URL = "blog" ###tbd
  ##weight = 4
  
  ##[[menu.footer]]
  ##name = "Impressum"
  ##URL = "pricing"
  ##weight = 4


[params]
logo = "images/uploads/VG_mu_logo_new.png" #"images/uploads/VG_Mu_logo.PNG" #"images/logoBlack.png"
home = "START"
# Contact Information
phone = "+43 650 3536751" ### Marlies Mürzl
email = "info@vinzi-wuestenrose.at"
location = "Baierdorf 115, A-8844 Schöder"
copyright = "&copy; 2021 Vinzenzgemeinschaft Murau"#2019 a theme by [themefisher](https://themefisher.com/)"
# Meta data
description = "Vinzenzgemeinschaft Bezirk Murau"
author = "Themefisher"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "Your ID"

  # Preloader
  [params.preloader]
  enable = true

  # Navigation top header
  [params.topHeader]
  enable = true

  # Navigation button
  [params.navBtn]
  enable = true
  label = "SPENDEN"
  link = "donation"

  # Subscription
  ##[params.subscription]
  ##title = "Newsletter"
  ##content = "Newsletter abonnieren und informiert bleiben"
  

  #################### social icon ######################################
  [[params.social]]
  name = "Facebook"
  icon = "ti-facebook" # themify icon pack https://themify.me/themify-icons
  link = "https://www.facebook.com/groups/1268422270243545"
  #"https://www.facebook.com/profile.php?id=100063577989432"
  
  ##[[params.social]]
  ##name = "Twitter"
  ##icon = "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
  ##link = "#"
  
  ##[[params.social]]
  ##name = "Vimeo"
  ##icon = "ti-vimeo-alt" # themify icon pack https://themify.me/themify-icons
  ##link = "#"
  
  ##[[params.social]]
  ##name = "Github"
  ##icon = "ti-github" # themify icon pack https://themify.me/themify-icons
  ##link = "#"
  
############################# post share links ######################
[[params.postShare]]
icon = "ti-facebook" # themify icon pack https://themify.me/themify-icons
name = "facebook"
link = "https://www.facebook.com/sharer.php?display=page&u=https://vinzi-wuestenrose.at"
#link = "https://www.facebook.com/sharer.php?u={{ $url }}"

[[params.postShare]]
icon = "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
name = "twitter"
link = "https://twitter.com/intent/tweet?hashtags=codingnconcepts&amp;url=https://vinzi-wuestenrose.at&amp;text={{ .Title }}"
#link = "https://twitter.com/intent/tweet?hashtags=codingnconcepts&amp;url={{ .Permalink }}&amp;text={{ .Title }}"

[[params.postShare]]
icon = "ti-linkedin" # themify icon pack https://themify.me/themify-icons
name = "linkedin"
link = "https://www.linkedin.com/shareArticle?mini=true&amp;url=https://vinzi-wuestenrose.at.app&amp;source=https://vinzi-wuestenrose.at&amp;title={{ $title }}&amp;summary={{ $title }}" 
#link = "https://www.linkedin.com/shareArticle?mini=true&amp;url={{ $url }}&amp;source={{ $url }}&amp;title={{ $title }}&amp;summary={{ $title }}" 

#[[params.postShare]]
#icon = "ti-pinterest" # themify icon pack https://themify.me/themify-icons
#name = "pinterest"
#link = "#"

[[params.postShare]]
icon = "ti-email" # themify icon pack https://themify.me/themify-icons
name = "email"
link = "mailto:?subject={{ .Site.Title }} - {{ $title }}.&amp;body={{ $body }}"

[[params.postShare]]
icon = "ti-mobile" # themify icon pack https://themify.me/themify-icons
name = "whatsapp"
link = "whatsapp://send?text={{ $body }}"

[markup.goldmark.renderer]
unsafe = true
# pictures
## bg: 1920x760
## blog: 400x300
## member: 600x600
## gallery: 150x150