backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Editorial Workflow (This line should *not* be indented)
publish_mode: editorial_workflow

# Media and Public Folders
media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Entwurf", name: "draft", widget: "boolean"}
      #- {label: "BG Image", name: "bgImage", widget: "image", required: false}
      - {label: "Bild", name: "image", widget: "image", required: false}
      - {label: "Gewichtung", name: "weight", widget: "number"}
      - {label: "Text", name: "body", widget: "markdown"}


